.TH "bug" 3 "Sun Oct 12 2025" "Linux Memeory Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBGlobal \fBMyLibrary::Example::test\fP (const std::string &test)\fP" 1c
example bug 
.IP "\fBGlobal \fBMyLibrary::SubclassExample< TemplatedClass >::virtualfunc\fP () override\fP" 1c
second bug 
.PP

