.TH "docs/theme/doxygen-awesome/include/MyLibrary/example.hpp" 3 "Sun Oct 12 2025" "Linux Memeory Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/theme/doxygen-awesome/include/MyLibrary/example.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMyLibrary::Example\fP"
.br
.RI "\fBExample\fP class to demonstrate the features of the custom CSS\&. "
.ti -1c
.RI "class \fBMyLibrary::SecondExample\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMyLibrary\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMyLibrary::Color\fP { \fBMyLibrary::red\fP = 1, \fBMyLibrary::green\fP = 2, \fBMyLibrary::blue\fP = 3 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Linux Memeory Manager from the source code\&.
