.TH "md_docs_theme_doxygen_awesome_docs_tricks" 3 "Sun Oct 12 2025" "Linux Memeory Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_theme_doxygen_awesome_docs_tricks \- Tips & Tricks 

.SH "Diagrams with Graphviz"
.PP
To get the best-looking class diagrams for your documentation, generate them with Graphviz as vector graphics and a transparent background:
.PP
.PP
.nf
# Doxyfile
HAVE_DOT = YES
DOT_IMAGE_FORMAT = svg
DOT_TRANSPARENT = YES
.fi
.PP
.PP
If \fCINTERACTIVE_SVG = YES\fP is set in the Doxyfile, all user-defined dotgraphs must be wrapped with the \fCinteractive_dotgraph\fP CSS class for them to be rendered correctly:
.PP
.PP
.nf
<div class="interactive_dotgraph">

\dotfile graph\&.dot

</div>
.fi
.PP
.PP
\fBNote\fP
.RS 4
Both the default overflow scrolling behavior in this theme and the interactive editor enabled by \fCINTERACTIVE_SVG\fP are, in my opinion, unsatisfying workarounds\&. Consider designing your graphs to be narrow enough to fit the page to avoid scrolling\&.
.RE
.PP
.SH "Disable Dark Mode"
.PP
If you don't want the theme to automatically switch to dark mode depending on the browser preference, you can disable dark mode by adding the \fClight-mode\fP class to the HTML tag in the header template:
.PP
.PP
.nf
<html xmlns="http://www\&.w3\&.org/1999/xhtml" class="light-mode">
.fi
.PP
.PP
The same can be done to always enable dark mode:
.PP
.PP
.nf
<html xmlns="http://www\&.w3\&.org/1999/xhtml" class="dark-mode">
.fi
.PP
.PP
\fBWarning\fP
.RS 4
This only works if you do not use the dark-mode toggle extension\&.
.RE
.PP
.SH "Choosing Sidebar Width"
.PP
If you have enabled the sidebar-only theme variant, make sure to carefully choose an appropriate width for your sidebar\&. It should be wide enough to hold the icon, project title, and version number\&. If the content is too wide, it will be cut off\&.
.PP
.PP
.nf
html {
    /* Make sure sidebar is wide enough to contain the page title (logo + title + version) */
    --side-nav-fixed-width: 335px;
}
.fi
.PP
.PP
The chosen width should also be set in the Doxyfile:
.PP
.PP
.nf
# Doxyfile
TREEVIEW_WIDTH = 335
.fi
.PP
.SH "Formatting Tables"
.PP
By default, tables in this theme are left-aligned and as wide as required to fit their content\&. These properties can be changed for individual tables\&.
.SS "Centering"
Tables can be centered by wrapping them in the \fC<center>\fP HTML tag\&.
.PP
.PP
.IP "\(bu" 2
Code ```md  This table   is centered    test 1   test 2    ```
.IP "\(bu" 2
Result  This table   is centered    test 1   test 2   
.PP
.PP
.SS "Full Width"
To make tables span the full width of the page, no matter how wide the content is, wrap the table in the \fCfull_width_table\fP CSS class\&.
.PP
\fBWarning\fP
.RS 4
Apply with caution! This breaks the overflow scrolling of the table\&. Content might be cut off on small screens!
.RE
.PP
.PP
.IP "\(bu" 2
Code ```md  This table   spans the full width    test 1   test 2    ```
.IP "\(bu" 2
Result  This table   spans the full width    test 1   test 2   
.PP
.PP
.SS "Buttons"
The theme comes with a custom class to add simple buttons:
.PP
.PP
.IP "\(bu" 2
Code ```md Click me! ```
.IP "\(bu" 2
Result Click me!
.PP
.PP
.SS "Bordered Images"
The \fCbordered_image\fP class can be used to add a neat rounded border around images in the documentation\&. With \fCdarkmode_inverted_image\fP the image is filtered to adapt to darkmode:
.PP
.PP
.IP "\(bu" 2
Code ```md 
.PP
 {width=250px}
.PP
  ```
.IP "\(bu" 2
Result  {width=250px} 
.PP
.PP
.PP
.PP
Previous   Next    \fBCustomization\fP   \fCExample\fP   
.PP
 
